[package]
name = "aws-mqtt-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.7"
lambda_runtime = "0.7"
tokio = { version = "1", features = ["macros"] }
aws-config = "0.54.1"
aws-sdk-iotdataplane = "0.24.0"
serde = {version = "1.0.146", features = ["derive"] }